"""Sweep blocking caps to find the recall the data can actually support.

The probe showed 61.6% of missed truth pairs were generated by the join and then
discarded by a cap, and that zero misses are signal-absent. So recall is limited by
configuration, not by the data. This sweeps the per-pass block caps and the per-S1
candidate cap against a fixed sample of Source 1 entities, reusing the cached keys so
each configuration costs about a minute.

Usage:
    python tools/exp_cap_sweep.py --n-s1 60000
"""
import argparse
import json
import sys
import time
from pathlib import Path

import numpy as np
import pandas as pd
import pyarrow.parquet as pq

sys.path.insert(0, "code/business_entity_resolution/src")
from ber.blocking import _join_sql, _pass_caps, block_keys, load_token_idf
from ber.config import Config
from ber.db import connect

BASE_CAPS = {1: 5000, 3: 300, 4: 3000, 5: 1000, 6: 50, 7: 600, 8: 300, 9: 200, 10: 60}


def log(m):
    print(f"[sweep] {m}", flush=True)


def load_sample(processed, gt_path, n_s1, seed):
    rng = np.random.default_rng(seed)
    gt = pd.read_parquet(gt_path)
    matched = set(gt.loc[gt.matched_entity_ids != "", "source1_entity_id"])
    chosen = set(rng.choice(sorted(matched), size=min(n_s1, len(matched)), replace=False))
    frames = []
    for batch in pq.ParquetFile(processed / "train_source1.parquet").iter_batches(
            batch_size=250_000):
        df = batch.to_pandas()
        hit = df[df.entity_id.isin(chosen)]
        if len(hit):
            frames.append(hit)
        if sum(len(f) for f in frames) >= len(chosen):
            break
    return pd.concat(frames, ignore_index=True)


def run_config(con, s1, cand_sql, s1k, cap, caps):
    con.unregister("s1k")
    con.execute("DROP VIEW IF EXISTS candk")
    con.execute("DROP TABLE IF EXISTS cand")
    con.register("s1k", s1k)
    con.execute(f"CREATE TEMP VIEW candk AS SELECT * FROM read_parquet({cand_sql})")
    con.execute(f"CREATE TEMP TABLE cand AS {_join_sql('s1k', 'candk', cap, caps)}")
    n = con.execute("SELECT COUNT(*) FROM cand").fetchone()[0]
    found = con.execute(
        "SELECT COUNT(*) FROM truth_ids WHERE (s1_id, cand_id) IN "
        "(SELECT s1_id, cand_id FROM (SELECT DISTINCT s1_id, cand_id FROM cand))"
    ).fetchone()[0]
    return n, found


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n-s1", type=int, default=60_000)
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--config", default="code/business_entity_resolution/config.json")
    ap.add_argument("--out", default="DATA/reports/cap_sweep.json")
    args = ap.parse_args()

    cfg = Config.load(args.config)
    data = Path(cfg.data_dir)
    processed = data / "processed"
    key_dir = data / "keys"
    idf_map, _ = load_token_idf(data / "reports" / "train_token_idf.json")

    cand_parts = [key_dir / f"train_source{s}_keys.parquet" for s in (2, 3)]
    cand_sql = "[" + ",".join(f"'{p.as_posix()}'" for p in cand_parts) + "]"

    log(f"sampling {args.n_s1} matched S1 entities")
    s1 = load_sample(processed, processed / "train_ground_truth.parquet", args.n_s1, args.seed)
    log(f"loaded {len(s1):,} S1 rows")
    s1k = block_keys(s1, idf_map, cfg.idf_min)

    con = connect(cfg)
    con.execute("PRAGMA max_temp_directory_size='20GiB'")
    con.execute("SET threads=2")
    con.execute(
        "CREATE TEMP TABLE truth_ids AS SELECT source1_entity_id AS s1_id, "
        "unnest(string_split(matched_entity_ids, ',')) AS cand_id "
        f"FROM read_parquet('{(processed / 'train_ground_truth.parquet').as_posix()}') "
        "WHERE matched_entity_ids <> ''"
    )
    total = con.execute(
        "SELECT COUNT(*) FROM truth_ids WHERE s1_id IN (SELECT entity_id FROM s1)"
    ).fetchone()[0]
    log(f"truth pairs for sample: {total:,}")

    # Isolate the per-S1 cap with block caps held at the shipped values. Sweeping both
    # together is misleading: widening passes 4/5 floods the per-S1 slots with address
    # collisions and evicts name-based true matches, so recall can fall while both caps
    # rise.
    configs = [
        ("tight blocks cap=200",   200, dict(BASE_CAPS)),
        ("tight blocks cap=400",   400, dict(BASE_CAPS)),
        ("tight blocks cap=800",   800, dict(BASE_CAPS)),
        ("tight blocks cap=1600", 1600, dict(BASE_CAPS)),
        ("tight blocks cap=3200", 3200, dict(BASE_CAPS)),
        ("name-passes only cap=1600", 1600, {**BASE_CAPS, 4: 300, 5: 200, 6: 20}),
        ("name-passes only cap=3200", 3200, {**BASE_CAPS, 4: 300, 5: 200, 6: 20}),
    ]

    results = []
    print(f"\n{'config':28s} {'cands/S1':>10s} {'cands(M)':>10s} {'recall':>8s} {'sec':>6s}")
    for label, cap, caps in configs:
        t0 = time.time()
        n_cand, found = run_config(con, s1, cand_sql, s1k, cap, caps)
        dt = time.time() - t0
        recall = found / max(total, 1)
        per_s1 = n_cand / max(len(s1), 1)
        results.append({"label": label, "cap": cap, "pass_caps": caps,
                        "candidates": n_cand, "candidates_per_s1": per_s1,
                        "found": found, "recall": recall, "seconds": dt})
        print(f"{label:28s} {per_s1:10.1f} {n_cand / 1e6:10.1f} {recall:8.4f} {dt:6.0f}",
              flush=True)
        if recall >= 0.99:
            log(f"*** reached 0.99 recall at '{label}' ***")
    con.close()

    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps({"truth_pairs": total, "n_s1": len(s1),
                               "results": results}, indent=2), encoding="utf-8")
    log(f"written {out}")


if __name__ == "__main__":
    main()
